name: Propose Changelog Update

on:
  # JuliaTagBot activated
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  propose-changelog:
    # Only when TagBot is activated, change the CHANGELOG
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # All git history
          fetch-depth: 0

      # Step 2
      - name: Generate cumulative CHANGELOG.md
        id: changelog_generator
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        #   output-file: "CHANGELOG.md"
          input-file: "CHANGELOG.md"
          version-file: "./Project.toml"
          skip-commit: true
          skip-tag: true
          git-push: false

      # Step 3
      - name: Create Pull Request with updated CHANGELOG.md
        if: steps.changelog_generator.outputs.skipped == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_FOR_CHANGELOG }}
          commit-message: "docs(changelog): update CHANGELOG.md"
          title: "Docs: Update CHANGELOG.md for new release"
          body: |
            This PR was automatically generated to update the `CHANGELOG.md` file for the upcoming release.

            Please review the changes and merge to trigger the final release.
          # Branch for changelog
          branch: "chore/update-changelog"
          # If exist, update
          delete-branch: true
