name: Run TagBot on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main 

jobs:
  tagbot:
    # When pr is merged and the branch's name is 'chore/update-changelog'
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'chore/update-changelog'
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2
      - name: Run TagBot
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
